
import { createHash } from 'crypto';
import prisma from "@/lib/db";
import { Prisma } from '@prisma/client';

export class IntegrityService {

    /**
     * Computes SHA-256 hash of a buffer.
     */

    static computeHash(buffer: Buffer): string {
        return createHash('sha256').update(buffer).digest('hex');
    }

    /**
     * 1. Initialize Report Log to get a UUID.
     * Status is implicitly PENDING as file_hash is initialized with a temporary placeholder or null.
     */
    static async initReportLog(userId: string, reportType: string, format: 'PDF' | 'XLSX', parameters: any): Promise<string> {
        const log = await prisma.reportLog.create({
            data: {
                created_by: userId,
                report_type: reportType,
                format: format,
                parameters: parameters ?? {},
                file_hash: 'PENDING_GENERATION'
            },
            select: { id: true }
        });
        return log.id;
    }

    /**
     * 2. Finalize Report Log with the actual file hash.
     */
    static async finalizeReportLog(logId: string, fileBuffer: Buffer) {
        const hash = this.computeHash(fileBuffer);

        return await prisma.reportLog.update({
            where: { id: logId },
            data: { file_hash: hash }
        });
    }




    /**
     * Logs the generation of a report to the database.
     * Guaranteed to be atomic: Data creation + Hash creation.
     */
    static async logReportGeneration(
        userId: string,
        reportType: string,
        format: 'PDF' | 'XLSX',
        parameters: any,
        fileBuffer: Buffer
    ) {
        const hash = this.computeHash(fileBuffer);

        return await prisma.reportLog.create({
            data: {
                created_by: userId,
                report_type: reportType,
                format: format,
                parameters: parameters ?? {},
                file_hash: hash
            }
        });
    }

    /**
     * Verifies if a given file buffer matches the recorded hash in the database.
     * Usage: When an auditor uploads a file to check if it was generated by us.
     */
    static async verifyReportIntegrity(reportLogId: string, fileBuffer: Buffer): Promise<{ isValid: boolean, storedHash: string, computedHash: string }> {
        const log = await prisma.reportLog.findUnique({
            where: { id: reportLogId }
        });

        if (!log) {
            throw new Error(`Report Log ${reportLogId} not found.`);
        }

        const computedHash = this.computeHash(fileBuffer);
        const isValid = computedHash === log.file_hash;

        return {
            isValid,
            storedHash: log.file_hash,
            computedHash
        };
    }
}
